version: '3.1'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3308"
    volumes:
      - devedojo_data:/var/lib/mysql

volumes:
  devedojo_data:


    #Remove tds os container
    #docker system prune -a